from elasticsearch import Elasticsearch

# # Connect to Elasticsearch
# es = Elasticsearch(['https://localhost:9200/'])

# # Check if the connection is successful
# if es.ping():
#     print('Connected to Elasticsearch')
# else:
#     print('Could not connect to Elasticsearch')

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "E3M+giS=_zFNpsvocN-0"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200/",
    ca_certs="/users/taniasarkar/Downloads/elasticsearch-8.7.0/config/certs/http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)


# Successful response!
client.info()
# {'name': 'instance-0000000000', 'cluster_name': ...}